### ISSUE TITLE
Allow more than one caldav server

### ISSUE THREAD

**Issue by Eeems** [tenJirka/reGenda#2]
It would be nice to allow more than one caldav server, so that you can pull in calendars from multiple sources.

**Comment by tenJirka** [comment]
Indeed, I would like to add this feature alongside support for calendars specified only by URL. This will also added possibility to connect Google, Outlook,... calendars.
I'll definitely focus on that in near future.

**Comment by tenJirka** [comment]
Support for more than one caldav server is currently being developed in `multiserver` branch. Should work fine, but I'm leaving it here for more testing. 
If you would like to try it, just download a and replace `.py` files from this branch in `/opt/usr/lib/reGenda/` and update your config as described in README.

Problem to consider is that adding more servers linearly increase launch time, because there is more connections required. Caldav module uses `requests` module, which as far as I know will not work in async function as desired so there can't be much done to improve for now.
